### ISSUE TITLE
RESTClient: extend paginators to handle the HTTP POST method

### ISSUE THREAD

**Issue by burnash** [dlt-hub/dlt#1359]
### Background

The current implementation of paginators in the RESTClient is designed to manage pagination through the HTTP GET method.

### Problem

Certain APIs require the use of the HTTP POST method to retrieve paginated data (typically used when the request involves sending a significant amount of data). For example, Notion's [Query a database](https://developers.notion.com/reference/post-database-query) uses JSON in the request body to filter and paginate data.

### Task

- [ ] Identify the paginator classes in the RESTClient that need to be extended to handle the HTTP POST method. The suspects are likely JSONResponsePaginator (aka JSONLinkPaginator) and JSONCursorPaginator.
- [ ] Modify the paginator classes to support the HTTP POST method. 
- [ ] Add tests
- [ ] Update the RESTClient documentation

**Comment by rudolfix** [comment]
@burnash should we close it?

**Comment by burnash** [comment]
@rudolfix no, it's not implemented yet.

**Comment by burnash** [comment]
`JSONResponseCursorPaginator` support for POST is implemented in #2446

**Comment by burnash** [comment]
Implemented in #2446. Most likely the only paginator needed to support POST method is `JSONResponseCursorPaginator`.
