### ISSUE TITLE
document how sources and resources can be customized and manipulated

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#188]
**Background**
Most of the customizations should not require changes in pipeline code (hacking). We already provide several ways to manipulate/change how pipeline is executed and that needs to be documented

**Tasks**
* [ ] document how to select/deselect resources (https://github.com/dlt-hub/dlt/blob/devel/docs/technical/create_pipeline.md#multiple-resources-and-resource-selection-when-loading)
* [ ] document how to attach transformations to resources (https://github.com/dlt-hub/dlt/blob/devel/docs/technical/create_pipeline.md#data-item-transformations)
* [ ] document how to add resources to existing sources at runtime

**Comment by z3z1ma** [comment]
```python
@dlt.resource(table_name=lambda event: event['type'])
def repo_events() -> Iterator[TDataItems]:
    yield item
```

One key part of resources is write dispositions. How can I say `issues` is an `append` resource and `pull_requests` is a `replace` disposition?
