### ISSUE TITLE
make `nullable` hint for a column schema optional and default it to True

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#198]
**Background**
Using `columns` argument on `dlt.resource` requires that both data type and nullable hints are specified. We also do not provide any check if the column definition is valid, `dlt` just fails later.

**Tasks**
* [x] when resource is created in `dlt/extract/decorators.py` validate the columns schema passed.
* [x] add validation function to `common/schema/utils.py` look at `new_column()` function. looks like we should use it
* [x] if `nullable` is not provided set it to True
* [x] if validation fails provide an user friendly exception message (include the resource name, column name, other useful info)

Tests
* [x] test the column schema validation function (if not yet tested)
* [ ] write a test in `tests/pipelines` for a few cases where columns are defined. try the valid and invalid cases. check the final schema in the pipeline if the column is there with the declared params.
* [x] test our failing case: `columns={"tags": {"data_type": "complex"}}` was failing, `columns={"tags": {"data_type": "complex", nullable=False}}` was not
