### ISSUE TITLE
[destination] implement loader for Snowflake with PUT stage

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#22]
**Background**
Implement Snowflake destination based on PUT stage. It will be quite similar to the `BigQuery` implementation (just simpler). 

**Tasks**
* [x] use `jsonl` as preferred type
* [x] use `PUT` to stage
* [x] allow option to remove files when COPY INTO succeeded.
* [x] our jsonl uses base64 to store binary so enable BINARY_FORMAT  in COPY INTO https://docs.snowflake.com/en/sql-reference/sql/copy-into-table
* [ ] fail on any error on COPY INTO, return up to 100 errors
* [x] i think you must use TRUNCATE for replace load, do TRUNCATE COPY in one transaction!
* [x] implement cluster hint with CLUSTER BY 

**Authentication**
Derived from ConnectionStringCredentials:
1. * [x] must understand sql alchemy syntax https://docs.snowflake.com/en/developer-guide/python-connector/sqlalchemy
2. * [x] should expose several query parameters as fields `warehouse` `role`
3. * [x] key pair auth should be supported https://docs.snowflake.com/en/developer-guide/python-connector/sqlalchemy#key-pair-authentication-support

**Tests**
1. * [ ] we should enable it as destination in tests. all tests using ALL_DESTINATIONS must pass
2. * [ ] it should pass the same common tests which BigQuery job client and sql client is passing
3. * [ ] note that to pass sql_client tests you'll need to map DBApi exceptions into 3 categories that dlt needs: relation not found, terminal exceptions, transient exceptions. see bigquery and postgres implementations. that's manual work

all in all writing the test suite is more work than the code here

**Comment by rudolfix** [comment]
@adrianbr if you have any comments to the ticket...
