### ISSUE TITLE
create a `staging` destination using `fsspec`

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#333]
**Background**
We'd like to have a destination that copies the files to a (typically) bucket - anything that `fsspec` supports. Such destination is useful in itself but will be needed as predecessor for other destinations that work with staging. Example is Redshift which right now uses INSERT to load data without staging, it should rather use COPY command which is way faster. See **Future Work** at the end.

**Tasks**
* [x] add new destination that copies files to places supported by `fsspec`
* [x] support for S3 and GCS should be tested
* [x] the trick to solve is that credentials depend on the file system type (we have GcpCredentials, AWS credentials should be implemented similarly and may be placed in the common). we may synthesize right credentials dynamically?
* [x] file layout is {dataset_name}/{schema_name}.{table_name}.{load_id}.{file_id}.{ext}}
* [x] we implement "append" by just copying the files
* [x] we implement "replace": we delete all the files that belong to resources that will be replaced. then append. there's code that does similar things but for merge. see #263 the logic is fairly identical to the logic of `dlt drop` command
* [x] `merge` fallsback to `append` except when there are no keys defined - then it fallsback to replace
* [x] destination should ask for fsspec to be added as extra. the things like `boto3` as well. we should not add those dependencies to the global deps
* [x] We may disregard the schema file and schema updates (we could copy actual schema to `_dlt_versions` table but that's optional)

**Implementation**
This destination does not expose sql client so it will not be able to sync state or expose sql client. We have checks in the `Pipeline` for that but that may be tested

**Tests**
* [x] we'll create test buckets and configure them in CI
* [x] destination tests like for `dummy` and other clients where we check `append`, `replace` and `merge`

**Future Work**
The idea for the destination is as follow:
- we'll add a new argument to `pipeline()` and `pipeline.run()` called `staging`. it can take any destination with matching configuration type (like `DestinationClientDwhConfiguration` is a warehouse configuration that supports sql clients)
- this destination is loaded before the main destination is
- the staging load ends with creating followup tasks for all copied files, basically we put references to copied files into the `new_jobs` again
- then the regular load happens. our existing destinations should be able to resolve reference files and generate COPY jobs instead of inserts (Redshift/BigQuery)

what is a reference: maybe a file that contains `fsspec` url and has `reference` extension keeping all the other elements intact? IDK yet
