### ISSUE TITLE
dlt deploy with airflow

### ISSUE THREAD

**Issue by AstrakhantsevaAA** [dlt-hub/dlt#351]
### Background

We want to make running dlt pipeliens with airflow using `dlt deploy airflow` command.

### Tasks

- [x] create templates with simple dag 
- [x] create templates for cloudbuild.yaml
- [x] generate a list of env variables to set up in the Airflow
- [x] generate and display secrets.toml to put in dlt_secrets_toml
- [x] add airflow to dlt deploy cli command
- [x]  run whole pipeline with gcp
- [x]  write tests as [https://github.com/dlt-hub/dlt/blob/devel/tests/cli/test_deploy_command.py](https://github.com/dlt-hub/dlt/blob/devel/tests/cli/test_deploy_command.py)

### Implementation details
`BaseTomlProvider` has now a nice method to write config values back to the document (`set_value`). To generate `secrets.toml` to display just write all the config data back to an empty instance. You'll probably need to create `MemoryTomlProvider` because base class is abstract.
