### ISSUE TITLE
enable dbt 1.5.0

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#458]
**Background**
dbt helper is tightly integrated with `dbt`. this happens in `dbt_utils.py`. after upgrade of dbt-core to 1.5.0 the interface to CLI commands chaged. it now uses `click` and tbh. looks like it will be harder to invoke commands with arguments and get status and results (no single dispatch method)

**Tasks**
* [x] enable support for 1.5.0
* [x] add 1.5.0 to tested versions
* [ ] bump default dependencies to 1.5.x and update DEFAULT_DBT_VERSION
* [x] all tests need to pass
* [x] keep the current architecture.
* [ ] motherduck destination requires 1.5.x `dbt-duckdb` test it locally but not enable on CI
