### ISSUE TITLE
Implement chunking transformer for Weaviate destination

### ISSUE THREAD

**Issue by burnash** [dlt-hub/dlt#576]
### Background

#532 introduced support for the Weaviate vector database to dlt. While the support allows users to include specific fields into a vector index and lets Weaviate generate embeddings for data, there is a limitation when dealing with large content. Oversized data requires chunking before it's submitted to Weaviate for processing.

### Objective

To provide a more seamless integration with Weaviate, we need to add a transformer that can chunk the data into manageable sizes. This transformer should be flexible, allowing users to define the chunking strategy based on specific heuristics.

### Tasks

- [ ]  Develop a transformer function that accepts input data and returns it in chunked form.
    - The transformer should have an interface that allows it to accept a custom function, which will define the chunking strategy.
    - Integrate functionality similar to the [text splitters](https://python.langchain.com/docs/modules/data_connection/document_transformers/#text-splitters) from LangChain  which can provide heuristic-based content splitting.
- [ ]  Include sample heuristics or functions that developers can use or customize for their chunking needs.
- [ ]  Update the docs to explain how to use the chunking transformer.

### Tests

- [ ] Unit Tests for the transformer
- [ ] Tests the integration with Weaviate destination

**Comment by zilto** [comment]
Chunking is a common operation when processing documents. dlt is well-suited to to process documents in a ELT pipeline, either using a `@dlt.resource` during extraction (E) or a `@dlt.transformation` to transform loaded data (T). We could have documentation and examples for these patterns. It would be nice to add such content to a "dlt contrib" package or platform

Though, I will close this issue as not currently planned. Text-splitting isn't solved by one-size-fits-all solutions (as shown by the many implementations in LangChain et al.). It would add more maintenance surface to dlt and would be redundant with other packages. Personally, I recommend the library `chonkie` which has a small dependency footprint.
