### ISSUE TITLE
replace pool executor with thread executor in load stage

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#699]
**Background**
We want to completely switch to futures-like executors for the stages of the pipeline. As reported there the pool executor is failing ie. in AWS Lambda. Same thing is reported by our users
https://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda/52339275#52339275

**Tasks**
1. [ ] Use thread executor instead of `ThreadPool` for load.py. Extend `run_pool` with new pool types or remove it altogether from `load.py`
2. [ ] Make sure that fallback to using no pool at tall when number of workers == 1 is kept
3. [ ] Update all the tests, esp. the dummy tests
