### ISSUE TITLE
implement missing arrow and data contracts tests

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#787]
**Tasks**

- [ ] - test basic pyarrow lib
- [ ] - test pyarrow normalize
- [ ] - define columns and then load arrow table with incorrect order
- [ ] - fix _dlt_load_id added only if needed
- [ ] - test discard value and discard row in nested json: discard row in child table that has another child table should discard data from descendants
- [ ] - test removal of x-normalizer tags (also when {})
- [ ] - pydantic nested model test
- [x] - ~allow Annotated when synthesizing models~
- [ ] - test freeze exception with Pydantic

**Comment by sh-rp** [comment]
Questions:
* What should we test with nested models on pydantic? Right now it is not implemented, so maybe this is the task?
